Prepared By

Asif Newaz, Lecturer, EEE, IUT

Ahmad Shafiullah, Lecturer, EEE, IUT

Data Structures are the basic building blocks of a programming language. The first step towards learning a programming language is to understand its data structures i.e. how data can be represented in that programming language.


Python is very easy to understand and quite similar to Matlab programming language that you are familiar with. We will first briefly look at the basic structures. Then we will move to some special libraries that we will need for developing an ML system.

### **Lists**

Python Lists are just like the arrays in Matlab, which is an ordered collection of data. It is very flexible as the items in a list do not need to be of the same type.

In [1]:
List = [1, 2,  3, "IUT", 2.3]
print(List)

[1, 2, 3, 'IUT', 2.3]


Indexing of python lists starts from 0, unlike Matlab where it starts from 1. Also unlike Matlab, you've to use square brackets for indexing.

In [2]:
# accessing a element from the list using index number
print("Accessing element from the list")
print(List[0])
print(List[3])

# accessing a element using negative indexing
print("Accessing element using negative indexing")

# print the last element of list
print(List[-1])

# print the third last element of list
print(List[-3])

Accessing element from the list
1
IUT
Accessing element using negative indexing
2.3
3


It can also contain another list inside it (list of lists). This is how you create a matrix in python.

In [29]:
a= [2,3,[0,9],[0,0,9,9]]
a

[2, 3, [0, 9], [0, 0, 9, 9]]

**Slicing array**

upper bound exclusive ---> does not inlcude the last one

negative indexing is also possible

In [4]:
print(List[2:4])
print(List[2:5])
print(List[2:])

[3, 'IUT']
[3, 'IUT', 2.3]
[3, 'IUT', 2.3]


In [5]:
print(List[:4])
print(List[:5])
print(List[2:-1])

[1, 2, 3, 'IUT']
[1, 2, 3, 'IUT', 2.3]
[3, 'IUT']


In [6]:
print(List[-1])
print(List[-2])


2.3
IUT


Changing array elements

In [30]:
print(a[2])
a[2] = 'max payne'
print(a)

[0, 9]
[2, 3, 'max payne', [0, 0, 9, 9]]


In [10]:
a[4]='alicient'
a

IndexError: list assignment index out of range

In [31]:
a.append('alicient')
a

[2, 3, 'max payne', [0, 0, 9, 9], 'alicient']

Python lists are less flexible than Matlab's array/matrix.

To have that kind of flexibility, you will need numpy array from numpy library which is developed keeping similarity with Matlab.



In [14]:
# use dot then tab to see all the available methods to that object
a.

SyntaxError: invalid syntax (Temp/ipykernel_12760/1405779438.py, line 2)

no need to memorize all the possible methods. use documentation to find what you are looking for.

## **Tuple**
Python Tuple is similar to list but Tuples are immutable in nature i.e. the elements in the tuple cannot be added or removed once created. Just like a List, a Tuple can also contain elements of various types.


In Python, tuples are created by placing a sequence of values separated by ‘comma’ with or without the use of parentheses for grouping of the data sequence.



1.   item assignment - not allowed
2.   add item - not allowed
3.   delete item - not allowed

you've to first convert it into list to do such operations.



In [15]:

# Creating a Tuple with
# the use of Strings
Tuple = ('IUT', 'Boardbazar')
print("\nTuple with the use of String: ")
print(Tuple)

# Creating a Tuple with the use of list
list1 = [1, 2, 4, 5, 6]
print("\nTuple using List: ")
Tuple = tuple(list1)
print(Tuple)

# Accessing element using indexing
print("First element of tuple")
print(Tuple[0])

# Accessing element from last negative indexing
print("\nLast element of tuple")
print(Tuple[-1])



Tuple with the use of String: 
('IUT', 'Boardbazar')

Tuple using List: 
(1, 2, 4, 5, 6)
First element of tuple
1

Last element of tuple
6


look at the error message

In [16]:
print(Tuple)
Tuple[2] = 'voldemort'
print(Tuple)

(1, 2, 4, 5, 6)


TypeError: 'tuple' object does not support item assignment

In [20]:
#Tuple.
Tuple.count(4)

1

python is an object-oriented programming language. so it creates an object upon which u can call on methods and have certain properties.

# Alias

In [32]:
a

[2, 3, 'max payne', [0, 0, 9, 9], 'alicient']

In [33]:
b=a

In [34]:
a.append('gray')
a

[2, 3, 'max payne', [0, 0, 9, 9], 'alicient', 'gray']

In [35]:
b

[2, 3, 'max payne', [0, 0, 9, 9], 'alicient', 'gray']

In [36]:
c=a.copy()
# makes a shallow copy

In [37]:
a.remove(3)
a

[2, 'max payne', [0, 0, 9, 9], 'alicient', 'gray']

In [38]:
b

[2, 'max payne', [0, 0, 9, 9], 'alicient', 'gray']

In [39]:
c

[2, 3, 'max payne', [0, 0, 9, 9], 'alicient', 'gray']

## **Dictionary**
Dictionary is used to store data values like a map, which, unlike other Data Types that hold only a single value as an element, Dictionary holds the key:value pair. Key-value is provided in the dictionary to make it more optimized.

Indexing of Python Dictionary is done with the help of keys. We can create a dictionary by using curly braces ({})

In [40]:
# Creating a Dictionary
Dict = {'Name': 'Jon Snow', 'Knowledge': 0}

print("Creating Dictionary: ")
print(Dict)

# accessing a element using key
print("Accessing a element using key:")
print(Dict['Name'])

# accessing a element using get()
# method
print("Accessing a element using get:")
print(Dict.get("Knowledge"))


Creating Dictionary: 
{'Name': 'Jon Snow', 'Knowledge': 0}
Accessing a element using key:
Jon Snow
Accessing a element using get:
0


In [41]:
Dict = {'Name': 'CC_01', 1: [1, 2, 3, 4]}

In [42]:
Dict.keys()

dict_keys(['Name', 1])

In [43]:
Dict.values()

dict_values(['CC_01', [1, 2, 3, 4]])

## **String**
Python Strings are an immutable array of characters. Python does not have a character data type unlike Matlab. It is somewhat similar to Matlab's string.

In [44]:
String = "Welcome to the ML/AI Lab"
print("Creating String: ")
print(String)

# Printing First character
print("\nFirst character of String is: ")
print(String[0])

# Printing Last character
print("\nLast character of String is: ")
print(String[-1])

Creating String: 
Welcome to the ML/AI Lab

First character of String is: 
W

Last character of String is: 
b


In [45]:
len (String)
# unlike Matlab

24

Strings are immutable

In [46]:
String[2]= 'w'

TypeError: 'str' object does not support item assignment

## **Libraries**
Python libraries are like toolboxes filled with various tools that help you do specific tasks without having to create everything from scratch. These libraries are designed to make coding easier and more efficient for students and professionals alike. Here's a brief overview of some popular Python libraries:

1. **NumPy**: Great for mathematical computations. It helps you work with large arrays and matrices and perform numerical operations quickly.

2. **Pandas**: A library for data analysis and manipulation. It makes handling large datasets easy and provides functions to clean, filter, and analyze data.

3. **Matplotlib**: Used for plotting and visualization. It allows you to create graphs, charts, and other visual representations of data.

4. **SciPy**: Builds on NumPy and provides tools for scientific computing. It includes functions for optimization, integration, and statistical analysis.

5. **Scikit-Learn**: A library for machine learning. It offers simple tools to create and test various machine learning models.

6. **TensorFlow**: A library for deep learning developed by Google. It's used to create neural networks for tasks like image recognition, natural language processing, and more.

7. **Beautiful Soup**: Helps with web scraping. You can use it to pull data from websites and work with HTML and XML files.

8. **Flask**: A lightweight web framework. It's great for building small to medium-sized web applications quickly.

9. **Django**: A more robust web framework for building large-scale web applications with database support and other complex features.

10. **Tkinter**: Allows you to create graphical user interfaces (GUIs) for your Python applications.


# Numpy

NumPy (Numerical Python) is a widely used library for numerical computations in Python. It provides support for large arrays and matrices, along with mathematical functions to operate on these arrays. It works in similiar way that you have learnt in Matlab.


to find similar functions as Matlab - see this documentation.
https://numpy.org/doc/stable/user/numpy-for-matlab-users.html


The import statement is used to bring code from a library, module, or another file into your current script. This allows you to use functions from that library.

In [47]:
import numpy as np

# Creating a 1-dimensional array
arr = np.array([1, 2, 3, 4, 5])
print(arr)

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Element-wise addition
c = a + b
print("This is output c = ", c)
#Dot Product
d =  a @ b
print(d)

[1 2 3 4 5]
This is output c =  [5 7 9]
32


In [48]:
c=[1,2,3]
d=[4,5,6]
c+d

[1, 2, 3, 4, 5, 6]

In [49]:
a = np.array([2, 5, 8])
print(a.ndim)
b= np.array([[1,2,3],[4,5,6]])
print(b.ndim)
print(b.shape)

1
2
(2, 3)


In [ ]:
a.

In [50]:
print(a.sum())
print(a.max())
print(a.min())
print(a.mean())
print(b%2)

15
8
2
5.0
[[1 0 1]
 [0 1 0]]


In [51]:
print(b)
b.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [52]:
#Indexing
X1= np.array([2,3])
print(X1)
print(X1[1])


X2= np.array([[2,3],[4,5],[6,7]])
print(X2)
print(X2[1])
print(X2[1,1])

[2 3]
3
[[2 3]
 [4 5]
 [6 7]]
[4 5]
5


In [53]:
X2[X2>5]

array([6, 7])

In [54]:
X2[:1,:]
# :1 means rows up to and not including 1
# : means all columns

array([[2, 3]])

In [55]:
print(X2[:,0])
print(X2[:,0:1])

[2 4 6]
[[2]
 [4]
 [6]]


## **Pandas**
Pandas is a popular data manipulation library in Python that makes it easy to work with structured data like spreadsheets and databases. What we can do with pandas:
1. Data Loading: Easily load data from various file formats like CSV, Excel, JSON, etc.
2. Data Cleaning: Handle missing data, duplicates, and inconsistencies.
3. Data Analysis: Perform statistical analysis and apply aggregation functions.
4. Data Manipulation: Filter, sort, group, and reshape data.
5. Data Visualization: Create simple plots and integrate with libraries like Matplotlib.

To work with data table, you will need Pandas library. pandas is built on top of numpy array.

In [56]:
import pandas as pd

**Pandas Series object**

index is automatically assigned

In [57]:
st= ['harry', 'ron', 'hermione']
st

['harry', 'ron', 'hermione']

In [58]:
ss= pd.Series(st)
ss

0       harry
1         ron
2    hermione
dtype: object

In [59]:
Dict = {'Name': 'Legion', 'category': 'cbm', 'character': 'david haller','identity': 'mutant'}
print(Dict)
ds= pd.Series(Dict)
ds

{'Name': 'Legion', 'category': 'cbm', 'character': 'david haller', 'identity': 'mutant'}


Name               Legion
category              cbm
character    david haller
identity           mutant
dtype: object

**Querying a series**

The loc method allows you to query rows and columns by label. The iloc method allows you to query rows and columns by integer position.

In [60]:
ds.iloc[2]

'david haller'

In [61]:
ds.loc['identity']

'mutant'

In [62]:
ds[2]

'david haller'

In [63]:
ds['Name']

'Legion'

In [64]:
ds['Name']='We are Legion'
ds

Name         We are Legion
category               cbm
character     david haller
identity            mutant
dtype: object

**Pandas DataFrame**

multiple columns. Similar to Matlab's table

In [67]:
data=pd.read_csv('data_01.csv')
data

name  gender           class
0    geralt    male         witcher
1     triss  female       sorceress
2  yennefer  female       sorceress
3      ciri  female       undefined
4     regis    male  higher vampire

In [ ]:
data[2]

In [69]:
data.iloc[2]

name       yennefer
gender       female
class     sorceress
Name: 2, dtype: object

In [ ]:
data.loc['triss']

In [71]:
data.loc[1]

name          triss
gender       female
class     sorceress
Name: 1, dtype: object

direct indexing possible

but for querying, use loc

In [72]:
data['name']

0      geralt
1       triss
2    yennefer
3        ciri
4       regis
Name: name, dtype: object

In [73]:
data[['name','class']]

name           class
0    geralt         witcher
1     triss       sorceress
2  yennefer       sorceress
3      ciri       undefined
4     regis  higher vampire

In [74]:
data.loc[:,['class']]

class
0         witcher
1       sorceress
2       sorceress
3       undefined
4  higher vampire

In [75]:
# add new column
data['characteristics']= ['badass', 'kind', 'nightmare', 'she-devil', 'old friend']

In [76]:
data

name  gender           class characteristics
0    geralt    male         witcher          badass
1     triss  female       sorceress            kind
2  yennefer  female       sorceress       nightmare
3      ciri  female       undefined       she-devil
4     regis    male  higher vampire      old friend

## **Function**
 Creating and calling functions in python is very similiar to Matlab. But we will likely not use any user defined functions, because python has well enriched libraries to call functions from.
 Start by defining the function using the def keyword, followed by the function name and any parameters it needs.

In [77]:
def sum(number1, number2):
    result = number1 + number2
    return result

In [78]:
sum_result = sum(55,57)
print(sum_result)


112


**Method**

Unlike matlab where u call a function using parenthesis, in python, u call it with a dot after the object.

for instance, here, n is an object --> collection of items --> numpy array

In [79]:
import numpy as np
a= np.array([2,5,1,1,5,7])
a

array([2, 5, 1, 1, 5, 7])

In [80]:
np.unique(a)

array([1, 2, 5, 7])

In [81]:
a.sum()

21

**Importing libraries**

https://scikit-learn.org/stable/modules/classes.html

look at preprocessing module

In [7]:
from sklearn.preprocessing import MinMaxScaler

In [8]:
from sklearn.preprocessing import *