**Prepared by**

**Asif Newaz**

**Lecturer, EEE, IUT**

In [ ]:
import pandas as pd
import numpy as np
import itertools

from sklearn.preprocessing import *
from sklearn.model_selection import *
from sklearn.metrics import *
from imblearn.metrics import *
from sklearn.impute import *

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier

from sklearn.ensemble import StackingClassifier
from mlxtend.classifier import StackingCVClassifier

from sklearn.neural_network import MLPClassifier


from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

import matplotlib.pyplot as plt

# Data

In [ ]:
data= pd.read_csv('titanic_train.csv')
data

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

# Target Variable

In [ ]:
y=data['Survived']
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

# Feature Variables

In [ ]:
x= data.drop(['Survived'],axis=1)
x

PassengerId  Pclass                                               Name  \
0              1       3                            Braund, Mr. Owen Harris   
1              2       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2              3       3                             Heikkinen, Miss. Laina   
3              4       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4              5       3                           Allen, Mr. William Henry   
..           ...     ...                                                ...   
886          887       2                              Montvila, Rev. Juozas   
887          888       1                       Graham, Miss. Margaret Edith   
888          889       3           Johnston, Miss. Catherine Helen "Carrie"   
889          890       1                              Behr, Mr. Karl Howell   
890          891       3                                Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
0      male  22.0      1      0         A/5 21171   7.2500   NaN        S  
1    female  38.0      1      0          PC 17599  71.2833   C85        C  
2    female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S  
3    female  35.0      1      0            113803  53.1000  C123        S  
4      male  35.0      0      0            373450   8.0500   NaN        S  
..      ...   ...    ...    ...               ...      ...   ...      ...  
886    male  27.0      0      0            211536  13.0000   NaN        S  
887  female  19.0      0      0            112053  30.0000   B42        S  
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S  
889    male  26.0      0      0            111369  30.0000  C148        C  
890    male  32.0      0      0            370376   7.7500   NaN        Q  

[891 rows x 11 columns]

# Remove features

unnecessary features/features with too many missing entries

In [ ]:
drop_col= ['PassengerId', 'Name', 'Ticket', 'Cabin']

In [ ]:
x= x.drop(drop_col,axis=1)
x

Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         3    male  22.0      1      0   7.2500        S
1         1  female  38.0      1      0  71.2833        C
2         3  female  26.0      0      0   7.9250        S
3         1  female  35.0      1      0  53.1000        S
4         3    male  35.0      0      0   8.0500        S
..      ...     ...   ...    ...    ...      ...      ...
886       2    male  27.0      0      0  13.0000        S
887       1  female  19.0      0      0  30.0000        S
888       3  female   NaN      1      2  23.4500        S
889       1    male  26.0      0      0  30.0000        C
890       3    male  32.0      0      0   7.7500        Q

[891 rows x 7 columns]

# Preprocessing

In [ ]:
x['Sex'] = x['Sex'].map( {'female': 1, 'male': 0} ).astype(int)
x.head()

Pclass  Sex   Age  SibSp  Parch     Fare Embarked
0       3    0  22.0      1      0   7.2500        S
1       1    1  38.0      1      0  71.2833        C
2       3    1  26.0      0      0   7.9250        S
3       1    1  35.0      1      0  53.1000        S
4       3    0  35.0      0      0   8.0500        S

In [ ]:
x['Embarked'] = x['Embarked'].map( {'S': 1, 'C': 0, 'Q':2} )
x.head()

Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0       3    0  22.0      1      0   7.2500       1.0
1       1    1  38.0      1      0  71.2833       0.0
2       3    1  26.0      0      0   7.9250       1.0
3       1    1  35.0      1      0  53.1000       1.0
4       3    0  35.0      0      0   8.0500       1.0

# Missing Entries

In [ ]:
x.isnull().sum()

Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

# Train-Test Split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=10)

In [ ]:
x_train

Pclass  Sex   Age  SibSp  Parch      Fare  Embarked
57        3    0  28.5      0      0    7.2292       0.0
717       2    1  27.0      0      0   10.5000       1.0
431       3    1   NaN      1      0   16.1000       1.0
633       1    0   NaN      0      0    0.0000       1.0
163       3    0  17.0      0      0    8.6625       1.0
..      ...  ...   ...    ...    ...       ...       ...
369       1    1  24.0      0      0   69.3000       0.0
320       3    0  22.0      0      0    7.2500       1.0
527       1    0   NaN      0      0  221.7792       1.0
125       3    0  12.0      1      0   11.2417       0.0
265       2    0  36.0      0      0   10.5000       1.0

[712 rows x 7 columns]

In [ ]:
x_test

Pclass  Sex   Age  SibSp  Parch      Fare  Embarked
590       3    0  35.0      0      0    7.1250       1.0
131       3    0  20.0      0      0    7.0500       1.0
628       3    0  26.0      0      0    7.8958       1.0
195       1    1  58.0      0      0  146.5208       0.0
230       1    1  35.0      1      0   83.4750       1.0
..      ...  ...   ...    ...    ...       ...       ...
456       1    0  65.0      0      0   26.5500       1.0
191       2    0  19.0      0      0   13.0000       1.0
603       3    0  44.0      0      0    8.0500       1.0
94        3    0  59.0      0      0    7.2500       1.0
766       1    0   NaN      0      0   39.6000       0.0

[179 rows x 7 columns]

In [ ]:
column_names= x.columns.values
column_names

array(['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked'],
      dtype=object)

# Imputation

In [ ]:
imp = SimpleImputer(missing_values=np.nan, strategy='mean')

In [ ]:
imp.fit(x_train)

SimpleImputer()

In [ ]:
x_train_imp= imp.fit_transform(x_train)
x_train_imp

array([[  3.        ,   0.        ,  28.5       , ...,   0.        ,
          7.2292    ,   0.        ],
       [  2.        ,   1.        ,  27.        , ...,   0.        ,
         10.5       ,   1.        ],
       [  3.        ,   1.        ,  29.66854419, ...,   0.        ,
         16.1       ,   1.        ],
       ...,
       [  1.        ,   0.        ,  29.66854419, ...,   0.        ,
        221.7792    ,   1.        ],
       [  3.        ,   0.        ,  12.        , ...,   0.        ,
         11.2417    ,   0.        ],
       [  2.        ,   0.        ,  36.        , ...,   0.        ,
         10.5       ,   1.        ]])

In [ ]:
x_test_imp= imp.transform(x_test)

In [ ]:
x_test_imp

array([[ 3.        ,  0.        , 35.        , ...,  0.        ,
         7.125     ,  1.        ],
       [ 3.        ,  0.        , 20.        , ...,  0.        ,
         7.05      ,  1.        ],
       [ 3.        ,  0.        , 26.        , ...,  0.        ,
         7.8958    ,  1.        ],
       ...,
       [ 3.        ,  0.        , 44.        , ...,  0.        ,
         8.05      ,  1.        ],
       [ 3.        ,  0.        , 59.        , ...,  0.        ,
         7.25      ,  1.        ],
       [ 1.        ,  0.        , 29.66854419, ...,  0.        ,
        39.6       ,  0.        ]])

In [ ]:
x_train_2= pd.DataFrame(x_train_imp)
x_train_2

0    1          2    3    4         5    6
0    3.0  0.0  28.500000  0.0  0.0    7.2292  0.0
1    2.0  1.0  27.000000  0.0  0.0   10.5000  1.0
2    3.0  1.0  29.668544  1.0  0.0   16.1000  1.0
3    1.0  0.0  29.668544  0.0  0.0    0.0000  1.0
4    3.0  0.0  17.000000  0.0  0.0    8.6625  1.0
..   ...  ...        ...  ...  ...       ...  ...
707  1.0  1.0  24.000000  0.0  0.0   69.3000  0.0
708  3.0  0.0  22.000000  0.0  0.0    7.2500  1.0
709  1.0  0.0  29.668544  0.0  0.0  221.7792  1.0
710  3.0  0.0  12.000000  1.0  0.0   11.2417  0.0
711  2.0  0.0  36.000000  0.0  0.0   10.5000  1.0

[712 rows x 7 columns]

In [ ]:
x_train_2= pd.DataFrame(x_train_imp, columns=column_names)
x_train_2

Pclass  Sex        Age  SibSp  Parch      Fare  Embarked
0       3.0  0.0  28.500000    0.0    0.0    7.2292       0.0
1       2.0  1.0  27.000000    0.0    0.0   10.5000       1.0
2       3.0  1.0  29.668544    1.0    0.0   16.1000       1.0
3       1.0  0.0  29.668544    0.0    0.0    0.0000       1.0
4       3.0  0.0  17.000000    0.0    0.0    8.6625       1.0
..      ...  ...        ...    ...    ...       ...       ...
707     1.0  1.0  24.000000    0.0    0.0   69.3000       0.0
708     3.0  0.0  22.000000    0.0    0.0    7.2500       1.0
709     1.0  0.0  29.668544    0.0    0.0  221.7792       1.0
710     3.0  0.0  12.000000    1.0    0.0   11.2417       0.0
711     2.0  0.0  36.000000    0.0    0.0   10.5000       1.0

[712 rows x 7 columns]

In [ ]:
x_test_2= pd.DataFrame(x_test_imp, columns=column_names)
x_test_2

Pclass  Sex        Age  SibSp  Parch      Fare  Embarked
0       3.0  0.0  35.000000    0.0    0.0    7.1250       1.0
1       3.0  0.0  20.000000    0.0    0.0    7.0500       1.0
2       3.0  0.0  26.000000    0.0    0.0    7.8958       1.0
3       1.0  1.0  58.000000    0.0    0.0  146.5208       0.0
4       1.0  1.0  35.000000    1.0    0.0   83.4750       1.0
..      ...  ...        ...    ...    ...       ...       ...
174     1.0  0.0  65.000000    0.0    0.0   26.5500       1.0
175     2.0  0.0  19.000000    0.0    0.0   13.0000       1.0
176     3.0  0.0  44.000000    0.0    0.0    8.0500       1.0
177     3.0  0.0  59.000000    0.0    0.0    7.2500       1.0
178     1.0  0.0  29.668544    0.0    0.0   39.6000       0.0

[179 rows x 7 columns]

# Normalization

In [ ]:
sc= StandardScaler()

In [ ]:
sc.fit(x_train_2)

StandardScaler()

In [ ]:
x_train_sc= sc.fit_transform(x_train_2)
x_train_sc

array([[ 8.25233303e-01, -7.53844771e-01, -9.00475598e-02, ...,
        -4.77849481e-01, -4.96597757e-01, -1.79410807e+00],
       [-3.76333388e-01,  1.32653305e+00, -2.05636975e-01, ...,
        -4.77849481e-01, -4.33020011e-01,  1.93125518e-01],
       [ 8.25233303e-01,  1.32653305e+00,  2.73770730e-16, ...,
        -4.77849481e-01, -3.24167322e-01,  1.93125518e-01],
       ...,
       [-1.57790008e+00, -7.53844771e-01,  2.73770730e-16, ...,
        -4.77849481e-01,  3.67382090e+00,  1.93125518e-01],
       [ 8.25233303e-01, -7.53844771e-01, -1.36153112e+00, ...,
        -4.77849481e-01, -4.18602861e-01, -1.79410807e+00],
       [-3.76333388e-01, -7.53844771e-01,  4.87899515e-01, ...,
        -4.77849481e-01, -4.33020011e-01,  1.93125518e-01]])

In [ ]:
x_test_sc= sc.transform(x_test_2)
x_test_sc

array([[ 8.25233303e-01, -7.53844771e-01,  4.10839905e-01, ...,
        -4.77849481e-01, -4.98623195e-01,  1.93125518e-01],
       [ 8.25233303e-01, -7.53844771e-01, -7.45054244e-01, ...,
        -4.77849481e-01, -5.00081043e-01,  1.93125518e-01],
       [ 8.25233303e-01, -7.53844771e-01, -2.82696585e-01, ...,
        -4.77849481e-01, -4.83640400e-01,  1.93125518e-01],
       ...,
       [ 8.25233303e-01, -7.53844771e-01,  1.10437639e+00, ...,
        -4.77849481e-01, -4.80643063e-01,  1.93125518e-01],
       [ 8.25233303e-01, -7.53844771e-01,  2.26027054e+00, ...,
        -4.77849481e-01, -4.96193447e-01,  1.93125518e-01],
       [-1.57790008e+00, -7.53844771e-01,  2.73770730e-16, ...,
        -4.77849481e-01,  1.32625214e-01, -1.79410807e+00]])

In [ ]:
x_train_3= pd.DataFrame(x_train_sc, columns=column_names)
x_train_3

Pclass       Sex           Age     SibSp     Parch      Fare  Embarked
0    0.825233 -0.753845 -9.004756e-02 -0.458505 -0.477849 -0.496598 -1.794108
1   -0.376333  1.326533 -2.056370e-01 -0.458505 -0.477849 -0.433020  0.193126
2    0.825233  1.326533  2.737707e-16  0.412044 -0.477849 -0.324167  0.193126
3   -1.577900 -0.753845  2.737707e-16 -0.458505 -0.477849 -0.637119  0.193126
4    0.825233 -0.753845 -9.762331e-01 -0.458505 -0.477849 -0.468737  0.193126
..        ...       ...           ...       ...       ...       ...       ...
707 -1.577900  1.326533 -4.368158e-01 -0.458505 -0.477849  0.709933 -1.794108
708  0.825233 -0.753845 -5.909350e-01 -0.458505 -0.477849 -0.496193  0.193126
709 -1.577900 -0.753845  2.737707e-16 -0.458505 -0.477849  3.673821  0.193126
710  0.825233 -0.753845 -1.361531e+00  0.412044 -0.477849 -0.418603 -1.794108
711 -0.376333 -0.753845  4.878995e-01 -0.458505 -0.477849 -0.433020  0.193126

[712 rows x 7 columns]

In [ ]:
x_test_3= pd.DataFrame(x_test_sc, columns=column_names)
x_test_3

Pclass       Sex           Age     SibSp     Parch      Fare  Embarked
0    0.825233 -0.753845  4.108399e-01 -0.458505 -0.477849 -0.498623  0.193126
1    0.825233 -0.753845 -7.450542e-01 -0.458505 -0.477849 -0.500081  0.193126
2    0.825233 -0.753845 -2.826966e-01 -0.458505 -0.477849 -0.483640  0.193126
3   -1.577900  1.326533  2.183211e+00 -0.458505 -0.477849  2.210950 -1.794108
4   -1.577900  1.326533  4.108399e-01  0.412044 -0.477849  0.985467  0.193126
..        ...       ...           ...       ...       ...       ...       ...
174 -1.577900 -0.753845  2.722628e+00 -0.458505 -0.477849 -0.121040  0.193126
175 -0.376333 -0.753845 -8.221139e-01 -0.458505 -0.477849 -0.384425  0.193126
176  0.825233 -0.753845  1.104376e+00 -0.458505 -0.477849 -0.480643  0.193126
177  0.825233 -0.753845  2.260271e+00 -0.458505 -0.477849 -0.496193  0.193126
178 -1.577900 -0.753845  2.737707e-16 -0.458505 -0.477849  0.132625 -1.794108

[179 rows x 7 columns]

# Training & testing

In [ ]:
knn= KNeighborsClassifier(n_neighbors=5,n_jobs=-1)
lr = LogisticRegression()
dt= DecisionTreeClassifier(random_state=10)

Results will change with a different random state --> stochastic nature

In [ ]:
knn.fit(x_train_3, y_train)

KNeighborsClassifier(n_jobs=-1)

In [ ]:
knn.score(x_train_3, y_train)

0.8609550561797753

In [ ]:
knn.score(x_test_3, y_test)

0.8324022346368715

In [ ]:
lr.fit(x_train_3, y_train)
print(lr.score(x_train_3, y_train))
print(lr.score(x_test_3, y_test))

0.797752808988764
0.8268156424581006


In [ ]:
dt.fit(x_train_3, y_train)
print(dt.score(x_train_3, y_train))
print(dt.score(x_test_3, y_test))

0.9859550561797753
0.7597765363128491


**Identify Issues**

# Making predictions

In [ ]:
x_test_3.iloc[1]

Pclass      0.825233
Sex        -0.753845
Age        -0.745054
SibSp      -0.458505
Parch      -0.477849
Fare       -0.500081
Embarked    0.193126
Name: 1, dtype: float64

In [ ]:
x_test_2.iloc[1]

Pclass       3.00
Sex          0.00
Age         20.00
SibSp        0.00
Parch        0.00
Fare         7.05
Embarked     1.00
Name: 1, dtype: float64

In [ ]:
y_test.iloc[1]

0

In [ ]:
knn.predict([x_test_3.iloc[1]])


D:\apps\anaconda\anaconda\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [ ]:
knn.predict_proba([x_test_3.iloc[1]])


D:\apps\anaconda\anaconda\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array([[1., 0.]])

In [ ]:
lr.predict_proba([x_test_3.iloc[1]])


D:\apps\anaconda\anaconda\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([[0.84654254, 0.15345746]])

In [ ]:
dt.predict_proba([x_test_3.iloc[1]])


D:\apps\anaconda\anaconda\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([[1., 0.]])

**Class Task**

Train the algorithms with different random state in the train-test split step.
Write the codes in the below code box

**Using Pipeline**

**Using Cross-validation**

To avoid data leakage and reduce variance

In [ ]:
from sklearn.pipeline import Pipeline

In [ ]:
pipe = Pipeline([('imp',SimpleImputer()),('scaler', StandardScaler()), ('lr', lr)])
result= cross_validate(pipe, x,y, cv = 10)
df= pd.DataFrame(result)
df

In [ ]:
df.mean(axis=0)